FROM python:3.10-slim

WORKDIR /app
COPY . .
RUN pip install -r requirements.txt
RUN mkdir -p /root/.basedosdados/templates && \
    mkdir -p /root/.basedosdados/credentials/ \
    mkdir /tmp/bases
WORKDIR /app/src
RUN chmod +x worker.sh
ENTRYPOINT ["./worker.sh"]
